apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  clusterName: cluster-1
  git:
    syncRepo: https://github.com/bershin/demo-cloud-sync
    secretType: none
    policyDir: policy